services:
  kafka-01:
    container_name: kafka-01
    image: apache/kafka:4.1.1
    ports:
     - 9092:9092
    restart: unless-stopped
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_LISTENERS: BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: BROKER://192.168.10.40:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  kafka_init-topics:
    container_name: kafka_init-topics
    image: quay.io/strimzi/kafka:latest-kafka-4.1.1
    command: [ "sh", "-c", "bin/kafka-topics.sh --create --topic logging.jamf.mvp.test --config compression.type=gzip --bootstrap-server kafka-01:9092"]
    depends_on:
      kafka-01:
        condition: service_started
  kafka-magic:
    image: digitsy/kafka-magic
    ports:
      - 8081:80
    volumes:
      - ./kafka-magic/:/config
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"
      KMAGIC_ALLOW_SCHEMA_DELETE: "true"
      KMAGIC_CONFIG_STORE_TYPE: "file"
      KMAGIC_CONFIG_STORE_CONNECTION: "Data Source=/config/KafkaMagicConfig.db;"
      KMAGIC_CONFIG_ENCRYPTION_KEY: "nokey"
  kafka-exporter:
    container_name: kafka-exporter
    image: danielqsj/kafka-exporter:v1.9.0
    ports:
      - 9308:9308
    command: ["--kafka.server=kafka-01:9092"]
    restart: unless-stopped
    depends_on:
      kafka-01:
        condition: service_started
  cadvisor-01:
    container_name: cadvisor-01
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    logging:
      driver: fluentd
      options:
        fluentd-address: "192.168.10.42:24224"
        fluentd-async: "true"
        tag: cadvisor-01
  dummy-caller:
    container_name: dummy_caller
    image: debian:trixie-slim
    restart: unless-stopped
    command: /bin/bash -c 'apt update && apt install -y curl && while true; do curl http://192.168.10.42:80; curl http://192.168.10.42:81; sleep 3; done'
