global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 5s
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.10.40:9100','192.168.10.41:9100','192.168.10.42:9100']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - '/etc/prometheus/http.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-01:9115
  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
          - '/etc/prometheus/cadvisor.yml'
  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.10.40:9308']
  - job_name: 'fluent-bit'
    static_configs:
      - targets: ['192.168.10.41:2021','192.168.10.42:2021']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['192.168.10.41:9114'] 
